### ISSUE TITLE
kak-lsp lives longer than kakoune instance that launched it

### ISSUE THREAD

**Issue by sgraf812** [kakoune-lsp/kakoune-lsp#599] opened 2022-03-23 16:21 UTC
Perhaps this is the same issue as #518. Unfortunately, I'm on nixos-21.11, so kak-lsp version 11.0.1. Here's the tail of the log that is produced. If you need more, I could provide it:

```
2022-03-23 16:52:58.439642425 [ThreadId 11384595] INFO hls:	finish: Wingman.getMetaprogramsAtSpan.TypeCheck (took 0.00s)
2022-03-23 16:52:58.447799275 [ThreadId 11384609] INFO hls:	finish: Wingman.getMetaprogramsAtSpan.TypeCheck (took 0.00s)
2022-03-23 16:52:58.460896148 [ThreadId 11384621] INFO hls:	finish: Wingman.getMetaprogramsAtSpan.TypeCheck (took 0.00s)
haskell-language-server-wrapper: callProcess: /nix/store/zxns8pq47ia7vmnq1fpnldizz5wg764f-haskell-language-server-1.4.0.0/bin/haskell-language-server-8.10.7 "--lsp" (exit -15): failed
, module: kak_lsp::language_server_transport:58
Mar 23 16:56:23.648 INFO ... Messages to language server terminated with ok, module: kak_lsp::thread_worker:21
Mar 23 16:56:23.648 INFO Waiting for Messages from language server to finish..., module: kak_lsp::thread_worker:19
Mar 23 16:56:23.648 INFO ... Messages from language server terminated with ok, module: kak_lsp::thread_worker:21
Mar 23 16:56:23.648 INFO Waiting for Language server errors to finish..., module: kak_lsp::thread_worker:19
Mar 23 16:56:23.648 INFO ... Language server errors terminated with ok, module: kak_lsp::thread_worker:21
Mar 23 17:13:47.818 DEBG From editor: 
session  = "2826996"
client   = ""
buffile  = ""
filetype = ""
version  = 0
method   = "stop"
[params]
, module: kak_lsp::editor_transport:129
Mar 23 17:13:47.818 INFO Shutting down language servers and exiting, module: kak_lsp::session:180
Mar 23 17:13:47.818 ERRO Failed to send stop message to language server, module: kak_lsp::session:183
Mar 23 17:13:47.818 INFO Exit haskell in project elided/ghc/unlifted, module: kak_lsp::session:185
Mar 23 17:13:47.818 INFO Waiting for Controller to finish..., module: kak_lsp::thread_worker:19
Mar 23 17:13:47.818 INFO ... Controller terminated with ok, module: kak_lsp::thread_worker:21
Mar 23 17:13:47.818 INFO Waiting for Messages to editor to finish..., module: kak_lsp::thread_worker:19
Mar 23 17:13:47.818 INFO ... Messages to editor terminated with ok, module: kak_lsp::thread_worker:21
Mar 23 17:13:47.826 INFO Starting main event loop, module: kak_lsp::session:28
Mar 23 17:13:47.826 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_HASKELL, module: kak_lsp::project_root:46
Mar 23 17:13:47.826 DEBG Routing editor request to Route { session: "2826996", language: "haskell", root: "elided/ghc/unlifted" }, module: kak_lsp::session:94
Mar 23 17:13:47.832 DEBG From editor: 
session  = "2826996"
client   = ""
buffile  = "elided/ghc/unlifted/compiler/GHC/Core/Opt/CprAnal.hs"
filetype = "haskell"
version  = 519
method   = "textDocument/didClose"
[params]
, module: kak_lsp::editor_transport:129
Mar 23 17:13:47.833 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_HASKELL, module: kak_lsp::project_root:46
Mar 23 17:13:47.833 DEBG Routing editor request to Route { session: "2826996", language: "haskell", root: "elided/ghc/unlifted" }, module: kak_lsp::session:94
Mar 23 17:13:47.836 DEBG From editor: 
session  = "2826996"
client   = ""
buffile  = "elided/ghc/unlifted/compiler/GHC/Core/Opt/WorkWrap/Utils.hs"
filetype = "haskell"
version  = 2582
method   = "textDocument/didClose"
[params]
, module: kak_lsp::editor_transport:129
Mar 23 17:13:47.836 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_HASKELL, module: kak_lsp::project_root:46
Mar 23 17:13:47.836 DEBG Routing editor request to Route { session: "2826996", language: "haskell", root: "elided/ghc/unlifted" }, module: kak_lsp::session:94
```

It seems that the haskell-language-server process failed, causing kak-lsp to zombie.

**Comment by krobelus** [comment] 2022-03-26 08:49
> haskell-language-server-wrapper: callProcess: /nix/store/zxns8pq47ia7vmnq1fpnldizz5wg764f-haskell-language-server-1.4.0.0/bin/haskell-language-server-8.10.7 "--lsp" (exit -15): failed

This is pretty weird, I wonder how to best recreate this scenario. I guess starting the language succeeds but at some point the process exits with failure.

> I think the first log line that is unexpected is
> 
> ```
> Mar 23 17:13:47.826 INFO Starting main event loop, module: kak_lsp::session:28
> ```

Right, it looks like kak-lsp tries to restart the language server to send the didClose notification.
However, the language server has already exited due to the error. Perhaps that leads to the deadlock.
We could add a hack to not restart the language server for closing notifications.
Though I'd like to know why exactly this happens.
I guess the first step is to find a reliable reproducer.

---

I also sometimes find a lingering kak-lsp process (though no zombies) that I have to pkill.
This happens with gopls (probably any  server), likely after a server timeout (default is 30 minutes).
I'll try to reproduce that with a low timeout.

**Comment by sgraf812** [comment] 2022-03-28 10:31
> I guess starting the language succeeds but at some point the process exits with failure.

Yes, this never seems to happen right at the start, only after some time has passed with kakoune open. Or perhaps while it's suspended (`Ctrl+Z`).

> This happens with gopls (probably any server), likely after a server timeout (default is 30 minutes).
I'll try to reproduce that with a low timeout.

Yes, that might be it, in combination with suspending kakoune. I never tweaked any timeout setting, though.

I just tried passing `--timeout 10` and suspended kakoune. It appears that `kak-lsp` will exit after 10s, but then is restarted once kakoune is brought into foreground again. I wonder if I can reproduce this issue with the lower timeout; perhaps the "zombie" (I agree that's an unfitting term) will kill itself after the timeout has run out and it won't actually live long enough for me to see it. Which is a workaround that is good enough for now, I suppose.

**Comment by clarfonthey** [comment] 2022-04-19 07:23
In my case, I pretty reliably end up with a lot of kak-lsp processes that are hanging after I quit kakoune. I frequently end up with `rust-analyzer` or other LSPs hanging, so, I use ctrl+C in kakoune to regain control and then :wq to exit and try again. The old process doesn't quit in this situation, and hangs, and I have to do `killall kak-lsp` to get rid of it manually.

I'm not sure what is happening in these situations, or what I can do to help prevent it.

**Comment by krobelus** [comment] 2022-04-19 09:40
Does that also happen before the timeout? (default is 30 minutes)

> I use ctrl+C in kakoune to regain control 

OK so you are using one of the *-sync requests and getting "Waiting for shell process to finish" from Kakoune?
I also get that sometimes with gopls (lsp-formatting-sync is sometimes really slow on a large monorepo) and need to manually kill kak-lsp.

A reliable reproducer would be much appreciated. I think for me it only happens after the language server goes dormant.

**Comment by krobelus** [comment] 2024-11-24 21:39
I think this is fixed

**Closed by krobelus** 2024-11-24 21:39 UTC
